'use client'

import Link from 'next/link'
import Sidebar from '../components/Sidebar'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white dark:from-gray-900 dark:via-gray-900 dark:to-black">
      <Sidebar />
      <div className="pl-0 lg:pl-64">
        <div className="max-w-3xl mx-auto px-4 sm:px-8 py-8">
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mb-8">Last updated: May 2026</p>

          <div className="prose prose-gray dark:prose-invert max-w-none space-y-6 text-gray-700 dark:text-gray-300 text-sm leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">1. Acceptance of Terms</h2>
              <p>By accessing or using AI Film Studio (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">2. Description of Service</h2>
              <p>AI Film Studio is an AI-powered film production platform that uses large language models and generative AI to create screenplays, storyboards, cast suggestions, location research, VFX planning, mood boards, and video content.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">3. User Accounts</h2>
              <p>You must register for an account to use the Service. You are responsible for maintaining the confidentiality of your credentials and for all activities under your account.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">4. User Content</h2>
              <p>You retain ownership of content you submit (prompts, uploaded files). You grant us a license to process your content solely to provide the Service. AI-generated outputs are provided &quot;as-is&quot; and may be used by you for any lawful purpose.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">5. Acceptable Use</h2>
              <p>You agree not to use the Service to generate content that is illegal, harmful, abusive, defamatory, or infringes on third-party rights. We reserve the right to suspend accounts that violate these terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">6. AI-Generated Content Disclaimer</h2>
              <p>Content generated by AI may contain inaccuracies, biases, or unexpected outputs. You are responsible for reviewing and validating all generated content before use in any production or publication.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">7. Intellectual Property</h2>
              <p>The Service, its design, branding, and underlying technology are the property of AI Film Studio. Third-party AI models and services are used under their respective licenses.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">8. Limitation of Liability</h2>
              <p>The Service is provided &quot;as is&quot; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">9. Modifications</h2>
              <p>We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">10. Contact</h2>
              <p>For questions about these terms, contact us at support@aifilmstudio.com.</p>
            </section>
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
            <Link href="/privacy" className="text-sm text-purple-600 dark:text-purple-400 hover:text-purple-500">
              View Privacy Policy &rarr;
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
